<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one or more
  ~ contributor license agreements.  See the NOTICE file distributed with
  ~ this work for additional information regarding copyright ownership.
  ~ The ASF licenses this file to You under the Apache License, Version 2.0
  ~ (the "License"); you may not use this file except in compliance with
  ~ the License.  You may obtain a copy of the License at
  ~
  ~      http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.jboss</groupId>
        <artifactId>jboss-parent</artifactId>
        <version>51</version>
    </parent>

    <groupId>org.wildfly.openssl</groupId>
    <artifactId>wildfly-openssl-natives-parent</artifactId>
    <version>2.3.1.CR1-SNAPSHOT</version>

    <packaging>pom</packaging>

    <name>WildFly OpenSSL Natives</name>
    <description>Project containing the WildFly OpenSSL Native builds</description>
    <url>hhttps://github.com/wildfly-security/wildfly-openssl-natives</url>

    <developers>
        <developer>
            <name>Darran Lofthouse</name>
            <email>darran.lofthouse@jboss.com</email>
            <organization>WildFly</organization>
            <organizationUrl>https://www.wildfly.org/</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:git@github.com:wildfly-security/wildfly-openssl-natives.git</connection>
        <developerConnection>scm:git:git@github.com:wildfly-security/wildfly-openssl-natives.git</developerConnection>
        <url>https://github.com/wildfly-security/wildfly-openssl-natives</url>
      <tag>HEAD</tag>
    </scm>

    <properties>
        <jdk.min.version>21</jdk.min.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <version.org.wildfly.checkstyle>1.0.8.Final</version.org.wildfly.checkstyle>
        <!-- Release Properties -->
        <nexus.repository.staging>wildfly-staging</nexus.repository.staging>
        <nexus.repository.release>wildfly-security</nexus.repository.release>
        <nexus.staging.tag>wildfly-openssl-natives-${project.version}</nexus.staging.tag>
    </properties>

    <licenses>
        <license>
            <name>Apache License 2.0</name>
            <url>http://repository.jboss.org/licenses/apache-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <build>
        <sourceDirectory>../../libwfssl/src</sourceDirectory>
    </build>

    <profiles>
        <!-- The native-build and package profiles are mutually exclusive.               -->
        <!--                                                                             -->
        <!-- The reason is some of the activations in the package profile are based      -->
        <!-- on files created by the native-build profile but resolution of the profiles -->
        <!-- to activate happens to soon in the build process so we run one at once.     -->
        <profile>
            <id>native-build</id>
            <activation>
                <property>
                    <name>native-build</name>
                </property>
            </activation>
            <modules>
                <module>build</module>
            </modules>
        </profile>
        <profile>
            <id>package</id>
            <activation>
                <property>
                    <name>!native-build</name>
                </property>
            </activation>
            <modules>
                <module>package</module>
            </modules>
        </profile>
    </profiles>
</project>
