<!--
  * Copyright The WildFly Authors
  * SPDX-License-Identifier: Apache-2.0
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.wildfly.openssl</groupId>
        <artifactId>wildfly-openssl-natives-parent</artifactId>
        <version>2.3.0.Alpha3-SNAPSHOT</version>
        <relativePath>../</relativePath>
    </parent>

    <groupId>org.wildfly.openssl</groupId>
    <artifactId>wildfly-openssl-natives-package</artifactId>
    <version>2.3.0.Alpha3-SNAPSHOT</version>

    <packaging>pom</packaging>

    <name>WildFly OpenSSL Natives - ${project.artifactId}</name>

    <build>
        <pluginManagement>
            <plugins>
            </plugins>
        </pluginManagement>
    </build>

    <profiles>
        <profile>
            <id>all</id>
            <activation>
                <file>
                    <exists>../target/lib</exists>
                </file>
            </activation>
            <modules>
                <module>all</module>
            </modules>
        </profile>
        <profile>
            <id>linux-aarch64</id>
            <activation>
                <file>
                    <exists>../target/lib/linux-aarch64</exists>
                </file>
            </activation>
            <modules>
                <module>linux-aarch64</module>
            </modules>
        </profile>
        <profile>
            <id>linux-i386</id>
            <activation>
                <file>
                    <exists>../target/lib/linux-i386</exists>
                </file>
            </activation>
            <modules>
                <module>linux-i386</module>
            </modules>
        </profile>
        <profile>
            <id>linux-ppc64le</id>
            <activation>
                <file>
                    <exists>../target/lib/linux-ppc64le</exists>
                </file>
            </activation>
            <modules>
                <module>linux-ppc64le</module>
            </modules>
        </profile>
        <profile>
            <id>linux-rhel8-x86_64</id>
            <activation>
                <file>
                    <exists>../target/lib/linux-rhel8-x86_64</exists>
                </file>
            </activation>
            <modules>
                <module>linux-rhel8-x86_64</module>
            </modules>
        </profile>
        <profile>
            <id>linux-rhel9-x86_64</id>
            <activation>
                <file>
                    <exists>../target/lib/linux-rhel9-x86_64</exists>
                </file>
            </activation>
            <modules>
                <module>linux-rhel9-x86_64</module>
            </modules>
        </profile>
        <profile>
            <id>linux-rhel10-x86_64</id>
            <activation>
                <file>
                    <exists>../target/lib/linux-rhel10-x86_64</exists>
                </file>
            </activation>
            <modules>
                <module>linux-rhel10-x86_64</module>
            </modules>
        </profile>
        <profile>
            <id>linux-s390x</id>
            <activation>
                <file>
                    <exists>../target/lib/linux-s390x</exists>
                </file>
            </activation>
            <modules>
                <module>linux-s390x</module>
            </modules>
        </profile>
        <profile>
            <id>linux-x86_64</id>
            <activation>
                <file>
                    <exists>../target/lib/linux-x86_64</exists>
                </file>
            </activation>
            <modules>
                <module>linux-x86_64</module>
            </modules>
        </profile>
        <profile>
            <id>macosx-aarch64</id>
            <activation>
                <file>
                    <exists>../target/lib/macosx-aarch64</exists>
                </file>
            </activation>
            <modules>
                <module>macosx-aarch64</module>
            </modules>
        </profile>
        <profile>
            <id>macosx-x86_64</id>
            <activation>
                <file>
                    <exists>../target/lib/macosx-x86_64</exists>
                </file>
            </activation>
            <modules>
                <module>macosx-x86_64</module>
            </modules>
        </profile>
        <profile>
            <id>solaris-sparcv9</id>
            <activation>
                <file>
                    <exists>../target/lib/solaris-sparcv9</exists>
                </file>
            </activation>
            <modules>
                <module>solaris-sparcv9</module>
            </modules>
        </profile>
        <profile>
            <id>solaris-x86_64</id>
            <activation>
                <file>
                    <exists>../target/lib/solaris-x86_64</exists>
                </file>
            </activation>
            <modules>
                <module>solaris-x86_64</module>
            </modules>
        </profile>
        <profile>
            <id>windows-i386</id>
            <activation>
                <file>
                    <exists>../target/lib/win-i386</exists>
                </file>
            </activation>
            <modules>
                <module>windows-i386</module>
            </modules>
        </profile>
        <profile>
            <id>windows-x86_64</id>
            <activation>
                <file>
                    <exists>../target/lib/win-x86_64</exists>
                </file>
            </activation>
            <modules>
                <module>windows-x86_64</module>
            </modules>
        </profile>

        <!-- Create an empty Javadoc jar -->
        <profile>
            <id>jboss-release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jar-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>empty-javadoc-jar</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                                <configuration>
                                    <classifier>javadoc</classifier>
                                    <classesDirectory>${basedir}/javadoc</classesDirectory>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

    </profiles>

</project>
